# apiVersion: v1
# kind: Service
# metadata:
#   name: your-app-service
# spec:
#   selector:
#     app: your-app
#   ports:
#     - protocol: TCP
#       port: 8085
#       targetPort: 3000
#   type: LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 3000
      nodePort: 30085
  type: NodePort
